/// Mapeo de nombres de selecciones nacionales a URLs de banderas PNG.
/// Fuente: flagcdn.com (CDN rápido, sin autenticación, imágenes PNG pequeñas).
String? footballFlagUrl(String teamName) {
  const codes = <String, String>{
    // América del Norte y Centroamérica
    'United States': 'us', 'USA': 'us',
    'Canada': 'ca',
    'Mexico': 'mx',
    'Costa Rica': 'cr',
    'Panama': 'pa',
    'Jamaica': 'jm',
    'Honduras': 'hn',
    'El Salvador': 'sv',
    'Guatemala': 'gt',
    'Trinidad and Tobago': 'tt',
    // América del Sur
    'Argentina': 'ar',
    'Brazil': 'br',
    'Uruguay': 'uy',
    'Colombia': 'co',
    'Ecuador': 'ec',
    'Peru': 'pe',
    'Chile': 'cl',
    'Paraguay': 'py',
    'Bolivia': 'bo',
    'Venezuela': 've',
    // Europa
    'France': 'fr',
    'Spain': 'es',
    'England': 'gb-eng',
    'Germany': 'de',
    'Portugal': 'pt',
    'Netherlands': 'nl',
    'Belgium': 'be',
    'Croatia': 'hr',
    'Switzerland': 'ch',
    'Denmark': 'dk',
    'Serbia': 'rs',
    'Ukraine': 'ua',
    'Austria': 'at',
    'Hungary': 'hu',
    'Slovenia': 'si',
    'Wales': 'gb-wls',
    'Scotland': 'gb-sct',
    'Turkey': 'tr',
    'Türkiye': 'tr',
    'Czech Republic': 'cz',
    'Czechia': 'cz',
    'Slovakia': 'sk',
    'Romania': 'ro',
    'Albania': 'al',
    'Georgia': 'ge',
    'Poland': 'pl',
    'Greece': 'gr',
    'Italy': 'it',
    'Sweden': 'se',
    'Norway': 'no',
    'Finland': 'fi',
    'Iceland': 'is',
    'Russia': 'ru',
    'Belarus': 'by',
    'Bosnia and Herzegovina': 'ba',
    'North Macedonia': 'mk',
    'Montenegro': 'me',
    'Kosovo': 'xk',
    'Ireland': 'ie',
    'Northern Ireland': 'gb-nir',
    'Luxembourg': 'lu',
    'Israel': 'il',
    'Cyprus': 'cy',
    'Malta': 'mt',
    'Faroe Islands': 'fo',
    'Lithuania': 'lt',
    'Latvia': 'lv',
    'Estonia': 'ee',
    'Moldova': 'md',
    'Bulgaria': 'bg',
    // Asia
    'Japan': 'jp',
    'Korea Republic': 'kr',
    'South Korea': 'kr',
    'Saudi Arabia': 'sa',
    'Australia': 'au',
    'Iran': 'ir',
    'Uzbekistan': 'uz',
    'Jordan': 'jo',
    'Qatar': 'qa',
    'Iraq': 'iq',
    'Indonesia': 'id',
    'Thailand': 'th',
    'China': 'cn',
    'China PR': 'cn',
    'Bahrain': 'bh',
    'UAE': 'ae',
    'United Arab Emirates': 'ae',
    'Kuwait': 'kw',
    'Oman': 'om',
    'Vietnam': 'vn',
    'Philippines': 'ph',
    'India': 'in',
    'Tajikistan': 'tj',
    'Kyrgyzstan': 'kg',
    'Kazakhstan': 'kz',
    'Syria': 'sy',
    'Palestine': 'ps',
    'Lebanon': 'lb',
    // África
    'Morocco': 'ma',
    'Senegal': 'sn',
    'South Africa': 'za',
    'Nigeria': 'ng',
    'Cameroon': 'cm',
    'Ghana': 'gh',
    "Côte d'Ivoire": 'ci',
    'Ivory Coast': 'ci',
    'Egypt': 'eg',
    'Tunisia': 'tn',
    'Mali': 'ml',
    'Algeria': 'dz',
    'Kenya': 'ke',
    'Tanzania': 'tz',
    'Ethiopia': 'et',
    'Uganda': 'ug',
    'Angola': 'ao',
    'Mozambique': 'mz',
    'Zimbabwe': 'zw',
    'Congo': 'cg',
    'DR Congo': 'cd',
    'Zambia': 'zm',
    "Guinea": 'gn',
    'Guinea-Bissau': 'gw',
    'Benin': 'bj',
    'Cape Verde': 'cv',
    'Burkina Faso': 'bf',
    'Niger': 'ne',
    'Gabon': 'ga',
    'Equatorial Guinea': 'gq',
    'Rwanda': 'rw',
    'Namibia': 'na',
    'Gambia': 'gm',
    'Mauritania': 'mr',
    'Libya': 'ly',
    'Sudan': 'sd',
    // Oceanía y otros
    'New Zealand': 'nz',
    'Fiji': 'fj',
    'Papua New Guinea': 'pg',
  };

  final code = codes[teamName];
  if (code == null) return null;
  return 'https://flagcdn.com/w80/$code.png';
}

/// Widget de bandera con placeholder y fade-in.
/// width/height son el tamaño lógico del rectángulo de la bandera.
// Uso: FlagImage(teamName: 'Argentina', width: 40, height: 28)
